/* Category  */
insert into category VALUES ('Выручить под процент', 'f', 0);
insert into category VALUES ('Выручить под залог', 'f', 0);
insert into category VALUES ('Обмен', 'f', 2);
insert into category VALUES ('Безвозвратно', 'f', 0);
insert into category VALUES ('Без %', 'f', 0);
insert into category VALUES ('Доля', 'f', 1);

/* Language */
insert into language VALUES ('Abkhaz', 'f');
insert into language VALUES ('Afar', 'f');
insert into language VALUES ('Afrikaans', 'f');
insert into language VALUES ('Akan', 'f');
insert into language VALUES ('Albanian', 'f');
insert into language VALUES ('Amharic', 'f');
insert into language VALUES ('Arabic', 'f');
insert into language VALUES ('Aragonese', 'f');
insert into language VALUES ('Armenian', 'f');
insert into language VALUES ('Assamese', 'f');
insert into language VALUES ('Avaric', 'f');
insert into language VALUES ('Avestan', 'f');
insert into language VALUES ('Aymara', 'f');
insert into language VALUES ('Azerbaijani', 'f');
insert into language VALUES ('Bambara', 'f');
insert into language VALUES ('Bashkir', 'f');
insert into language VALUES ('Basque', 'f');
insert into language VALUES ('Belarusian', 'f');
insert into language VALUES ('Bengali', 'f');
insert into language VALUES ('Bihari', 'f');
insert into language VALUES ('Bislama', 'f');
insert into language VALUES ('Bosnian', 'f');
insert into language VALUES ('Breton', 'f');
insert into language VALUES ('Bulgarian', 'f');
insert into language VALUES ('Burmese', 'f');
insert into language VALUES ('Catalan; Valencian', 'f');
insert into language VALUES ('Chamorro', 'f');
insert into language VALUES ('Chechen', 'f');
insert into language VALUES ('Chichewa; Chewa; Nyanja', 'f');
insert into language VALUES ('Chinese', 'f');
insert into language VALUES ('Chuvash', 'f');
insert into language VALUES ('Cornish', 'f');
insert into language VALUES ('Corsican', 'f');
insert into language VALUES ('Cree', 'f');
insert into language VALUES ('Croatian', 'f');
insert into language VALUES ('Czech', 'f');
insert into language VALUES ('Danish', 'f');
insert into language VALUES ('Divehi; Dhivehi; Maldivian;', 'f');
insert into language VALUES ('Dutch', 'f');
insert into language VALUES ('English', 'f');
insert into language VALUES ('Esperanto', 'f');
insert into language VALUES ('Estonian', 'f');
insert into language VALUES ('Ewe', 'f');
insert into language VALUES ('Faroese', 'f');
insert into language VALUES ('Fijian', 'f');
insert into language VALUES ('Finnish', 'f');
insert into language VALUES ('French', 'f');
insert into language VALUES ('Fula; Fulah; Pulaar; Pular', 'f');
insert into language VALUES ('Galician', 'f');
insert into language VALUES ('Georgian', 'f');
insert into language VALUES ('German', 'f');
insert into language VALUES ('Greek, Modern', 'f');
insert into language VALUES ('Guaraní', 'f');
insert into language VALUES ('Gujarati', 'f');
insert into language VALUES ('Haitian; Haitian Creole', 'f');
insert into language VALUES ('Hausa', 'f');
insert into language VALUES ('Hebrew (modern)', 'f');
insert into language VALUES ('Herero', 'f');
insert into language VALUES ('Hindi', 'f');
insert into language VALUES ('Hiri Motu', 'f');
insert into language VALUES ('Hungarian', 'f');
insert into language VALUES ('Interlingua', 'f');
insert into language VALUES ('Indonesian', 'f');
insert into language VALUES ('Interlingue', 'f');
insert into language VALUES ('Irish', 'f');
insert into language VALUES ('Igbo', 'f');
insert into language VALUES ('Inupiaq', 'f');
insert into language VALUES ('Ido', 'f');
insert into language VALUES ('Icelandic', 'f');
insert into language VALUES ('Italian', 'f');
insert into language VALUES ('Inuktitut', 'f');
insert into language VALUES ('Japanese', 'f');
insert into language VALUES ('Javanese', 'f');
insert into language VALUES ('Kalaallisut, Greenlandic', 'f');
insert into language VALUES ('Kannada', 'f');
insert into language VALUES ('Kanuri', 'f');
insert into language VALUES ('Kashmiri', 'f');
insert into language VALUES ('Kazakh', 'f');
insert into language VALUES ('Khmer', 'f');
insert into language VALUES ('Kikuyu, Gikuyu', 'f');
insert into language VALUES ('Kinyarwanda', 'f');
insert into language VALUES ('Kirghiz, Kyrgyz', 'f');
insert into language VALUES ('Komi', 'f');
insert into language VALUES ('Kongo', 'f');
insert into language VALUES ('Korean', 'f');
insert into language VALUES ('Kurdish', 'f');
insert into language VALUES ('Kwanyama, Kuanyama', 'f');
insert into language VALUES ('Latin', 'f');
insert into language VALUES ('Luxembourgish, Letzeburgesch', 'f');
insert into language VALUES ('Luganda', 'f');
insert into language VALUES ('Limburgish, Limburgan, Limburger', 'f');
insert into language VALUES ('Lingala', 'f');
insert into language VALUES ('Lao', 'f');
insert into language VALUES ('Lithuanian', 'f');
insert into language VALUES ('Luba-Katanga', 'f');
insert into language VALUES ('Latvian', 'f');
insert into language VALUES ('Manx', 'f');
insert into language VALUES ('Macedonian', 'f');
insert into language VALUES ('Malagasy', 'f');
insert into language VALUES ('Malay', 'f');
insert into language VALUES ('Malayalam', 'f');
insert into language VALUES ('Maltese', 'f');
insert into language VALUES ('Māori', 'f');
insert into language VALUES ('Marathi (Marāṭhī)', 'f');
insert into language VALUES ('Marshallese', 'f');
insert into language VALUES ('Mongolian', 'f');
insert into language VALUES ('Nauru', 'f');
insert into language VALUES ('Navajo, Navaho', 'f');
insert into language VALUES ('Norwegian Bokmål', 'f');
insert into language VALUES ('North Ndebele', 'f');
insert into language VALUES ('Nepali', 'f');
insert into language VALUES ('Ndonga', 'f');
insert into language VALUES ('Norwegian Nynorsk', 'f');
insert into language VALUES ('Norwegian', 'f');
insert into language VALUES ('Nuosu', 'f');
insert into language VALUES ('South Ndebele', 'f');
insert into language VALUES ('Occitan', 'f');
insert into language VALUES ('Ojibwe, Ojibwa', 'f');
insert into language VALUES ('Old Slavonic', 'f');
insert into language VALUES ('Oromo', 'f');
insert into language VALUES ('Oriya', 'f');
insert into language VALUES ('Ossetian, Ossetic', 'f');
insert into language VALUES ('Panjabi, Punjabi', 'f');
insert into language VALUES ('Pāli', 'f');
insert into language VALUES ('Persian', 'f');
insert into language VALUES ('Polish', 'f');
insert into language VALUES ('Pashto, Pushto', 'f');
insert into language VALUES ('Portuguese', 'f');
insert into language VALUES ('Quechua', 'f');
insert into language VALUES ('Romansh', 'f');
insert into language VALUES ('Kirundi', 'f');
insert into language VALUES ('Romanian, Moldavian, Moldovan', 'f');
insert into language VALUES ('Russian', 'f');
insert into language VALUES ('Sanskrit (Saṁskṛta)', 'f');
insert into language VALUES ('Sardinian', 'f');
insert into language VALUES ('Sindhi', 'f');
insert into language VALUES ('Northern Sami', 'f');
insert into language VALUES ('Samoan', 'f');
insert into language VALUES ('Sango', 'f');
insert into language VALUES ('Serbian', 'f');
insert into language VALUES ('Scottish Gaelic; Gaelic', 'f');
insert into language VALUES ('Shona', 'f');
insert into language VALUES ('Sinhala, Sinhalese', 'f');
insert into language VALUES ('Slovak', 'f');
insert into language VALUES ('Slovene', 'f');
insert into language VALUES ('Somali', 'f');
insert into language VALUES ('Southern Sotho', 'f');
insert into language VALUES ('Spanish; Castilian', 'f');
insert into language VALUES ('Sundanese', 'f');
insert into language VALUES ('Swahili', 'f');
insert into language VALUES ('Swati', 'f');
insert into language VALUES ('Swedish', 'f');
insert into language VALUES ('Tamil', 'f');
insert into language VALUES ('Telugu', 'f');
insert into language VALUES ('Tajik', 'f');
insert into language VALUES ('Thai', 'f');
insert into language VALUES ('Tigrinya', 'f');
insert into language VALUES ('Tibetan Standard, Tibetan, Central', 'f');
insert into language VALUES ('Turkmen', 'f');
insert into language VALUES ('Tagalog', 'f');
insert into language VALUES ('Tswana', 'f');
insert into language VALUES ('Tonga (Tonga Islands)', 'f');
insert into language VALUES ('Turkish', 'f');
insert into language VALUES ('Tsonga', 'f');
insert into language VALUES ('Tatar', 'f');
insert into language VALUES ('Twi', 'f');
insert into language VALUES ('Tahitian', 'f');
insert into language VALUES ('Uighur, Uyghur', 'f');
insert into language VALUES ('Ukrainian', 'f');
insert into language VALUES ('Urdu', 'f');
insert into language VALUES ('Uzbek', 'f');
insert into language VALUES ('Venda', 'f');
insert into language VALUES ('Vietnamese', 'f');
insert into language VALUES ('Volapük', 'f');
insert into language VALUES ('Walloon', 'f');
insert into language VALUES ('Welsh', 'f');
insert into language VALUES ('Wolof', 'f');
insert into language VALUES ('Western Frisian', 'f');
insert into language VALUES ('Xhosa', 'f');
insert into language VALUES ('Yiddish', 'f');
insert into language VALUES ('Yoruba', 'f');
insert into language VALUES ('Zhuang, Chuang', 'f');


